version: '3.7'
services:
  server: 
    build: api
    image: damiasmith/greens-over-grains-api
    ports:
      - '0.0.0.0.3000:3000'
  client:
    build: client
    image: damiasmith/greens-over-grains-app
    ports:
      - '80:80'
    environment:
      SERVER_ENV: production